// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddtsuqfivvipijvyvpbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdHN1cWZpdnZpcGlqdnl2cGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwODg2NjEsImV4cCI6MjA1NDY2NDY2MX0.4Qmvn2aF8WBrQAnaifP49q1MfSE5chwETtbCMZtJc8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);